<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="9.4.0"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>2092b3fb-6312-449e-bb8b-dd946d8c4923</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Altemiq.Aspire.Hosting.MinIO" Version="9.5.2" />
        <PackageReference Include="Aspire.Hosting.AppHost" Version="9.4.0"/>
        <PackageReference Include="Aspire.Hosting.SqlServer" Version="9.4.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BadmintonEcommerce.API\BadmintonEcommerce.API.csproj" />
    </ItemGroup>

</Project>
