name: .NET CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  checks: write
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.313

      # Restore
      - name: Restore dependencies
        run: dotnet restore

      # Build
      - name: Build solution
        run: dotnet build --no-restore

      # Run unit tests + coverage + trx report
      - name: Run tests
        run: >
          dotnet test
          --no-build
          --collect:"XPlat Code Coverage"
          --logger "trx"
          --results-directory ./TestResults

      # Upload raw test results
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ./TestResults

      # Publish readable test report on GitHub UI
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Test Results
          path: ./TestResults/**/*.trx
          reporter: dotnet-trx

      # Install report generator
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      # Generate HTML coverage report
      - name: Generate Coverage Report
        run: >
          reportgenerator
          -reports:./TestResults/**/coverage.cobertura.xml
          -targetdir:./CoverageReport
          -reporttypes:Html

      # Upload coverage report artifact
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./CoverageReport